### ISSUE TITLE
May I ask if it is possible to consider using time naming to sort the synchronized file notes.

### ISSUE THREAD

**Issue by i-iooi-i** [hyoban/obsidian-memos-plugin#1]
![image](https://github.com/hyoban/obsidian-memos-plugin/assets/1827701/f7bb2b1f-ab31-4114-9247-34f7b875c1b2)

As shown in the above figure, this naming may not seem very intuitive and it is not easy to find a particular note. If time is used to name notes, it seems more convenient to locate note information. 😊

![image](https://github.com/hyoban/obsidian-memos-plugin/assets/1827701/bc03d3ea-b26c-4b96-af0f-6550da2d94df)

Additionally, there is an idea to consider synchronizing notes every month, where all note information within a month is included in a sub note. This looks more complete and easier to read. However。
 it seems difficult to achieve. 😂

**Comment by hyoban** [comment]
I think it will be better to keep one memo in one file, then use a folder or tag to classify the file monthly

**Comment by hyoban** [comment]
Released version 1.1.0, which supports id, creat time, update time, first line text title as filename
