### ISSUE TITLE
Please add the access token feature to access memos.

### ISSUE THREAD

**Issue by njwander** [hyoban/obsidian-memos-plugin#12]
<img width="816" alt="image" src="https://github.com/hyoban/obsidian-memos-plugin/assets/8213705/943183c7-826e-4d1c-9b4c-26ea68c9ac2d">

https://github.com/usememos/memos/issues/1921#issuecomment-1720318524

In the latest Docker image, the Open API has disappeared. Please add the access token feature to access memos.

Below are my account settings.
<img width="1033" alt="image" src="https://github.com/hyoban/obsidian-memos-plugin/assets/8213705/8dbe2f21-555e-4a4e-9c3f-4203af1694c5">

**Comment by hyoban** [comment]
Thanks, it should be possible in version 1.1.3
