### ISSUE TITLE
手机上不能使用吗  为什么我不能启用插件

### ISSUE THREAD

**Issue by bbcghh123** [hyoban/obsidian-memos-plugin#3]
手机上不能使用吗  为什么我不能启用插件
![Screenshot_20230608-075354_Obsidian](https://github.com/hyoban/obsidian-memos-plugin/assets/98581999/0e988685-6b83-4d60-bd4a-57292f51574c)

**Comment by hyoban** [comment]
应该是配置的原因，我默认只允许桌面端了，没在手机上测试
https://github.com/hyoban/obsidian-memos-plugin/blob/main/manifest.json#L9

**Comment by bbcghh123** [comment]
大佬，怎么搞，
https://github.com/usememos/memos
大佬能不能进入这个电报群

**Comment by hyoban** [comment]
抱歉，忘记回复了，我在这个群里。因为需要 node 环境，所以需要桌面端
