### ISSUE TITLE
不支持memos v0.13.2和Obsidian1.3.5

### ISSUE THREAD

**Issue by cuiyanjie** [hyoban/obsidian-memos-plugin#5]
在arm mac obsidian 上使用此插件，对接了Memo的OpenAPI，提示Failed to sync memos. Please check your OpenAPI key and network.
![](https://dropovercl.s3.amazonaws.com/11312540-51b5-4531-80f9-f994c7a093e2/999462f9-65f5-4310-a475-c63dd167e8b9/537b6724-17c4-4aa9-9149-df2bff0b9a43.png)
Memos 的 Telegram群里今天好几个小伙伴都测试了一下。
![](https://dropovercl.s3.amazonaws.com/90219b40-5261-4850-8e19-66106d7c019c/a5423312-0147-4fb7-9801-8bea8c587354/ae605a75-db6d-46f7-a347-d467e1c1a270.png)

**Comment by hyoban** [comment]
已复现，我排查一下

**Comment by hyoban** [comment]
感觉还是 OpenAPI 的问题啊，你看看你的 OpenAPI 在浏览器里能不能正常访问

**Comment by cuiyanjie** [comment]
可以访问，在kirika里也不行，后来我觉得可能是反向代理的问题，我把API里面的 https://xxx.com/部分换成了http和IP+端口，在kirika里成功了，但Obsidian里如法炮制后还是不行。不管是Memos里直接生成的OpenAPI还是我手动替换成http://IP+端口的OpenAPI在浏览器里是可以访问的。

**Comment by hyoban** [comment]
ob 里面插件的版本是 1.0.3 吗

**Comment by hyoban** [comment]
方便在 tg 上私聊发送你的 openapi 我看看吗

**Comment by cuiyanjie** [comment]
是的103，刚更新的。可以私聊

**Comment by cuiyanjie** [comment]
没找到您的tg，我的 @elsa455333

**Comment by hyoban** [comment]
在1.0.4中被修复，原因是ob的插件网络请求是有浏览器环境的，跨域了。
