### ISSUE TITLE
Feature request:过滤已归档的memo；obsidian中按日期分文件写入。

### ISSUE THREAD

**Issue by ifeitao** [hyoban/obsidian-memos-plugin#6]
本来想要不要开发一个插件，发现已经有大佬动手了。提两个建议供参考：
1. 建议增加一个选项，可以过滤已归档的memo，不进行同步；
2. 在obsidian端，内容可以按日期写入文件而不是一条memo一个文件，或者可以写到daily note 中的一个block中去。

**Comment by hyoban** [comment]
1.1.0 增加了自定义文件名格式的功能
1.1.1 默认忽略归档的memos
