### ISSUE TITLE
插件1.0.6版本无法同步

### ISSUE THREAD

**Issue by tsaoshuang** [hyoban/obsidian-memos-plugin#7]
![image](https://github.com/hyoban/obsidian-memos-plugin/assets/7597482/c1cc6e1f-b09a-4b75-b755-5650fa545728)
![image](https://github.com/hyoban/obsidian-memos-plugin/assets/7597482/6eec6db4-6b5a-479c-b7c6-be7102c35d23)
无论api框里面填不填网址（带网址或单独的api）都提示api不正确 无法同步，之前一直是能用的，有一天突然不能用，ob版本是1.3.7

**Comment by ovaso** [comment]
同遇到这个问题, ob版本也一样

**Comment by hyoban** [comment]
我这里是可以的，你填入的链接是类似 `http://localhost:5230/api/v1/memo?openId=0844bd4f-2a0c-4d68-960f-f80382457f8a` 或是 `http://localhost:5230/api/memo?openId=33c3700d-831e-4bc7-baba-0a656ee32b2b` 这样的吗？

如果方便的话你可以单独发我你的链接，我帮你测试一下

**Comment by tsaoshuang** [comment]
> 我这里是可以的，你填入的链接是类似 `http://localhost:5230/api/v1/memo?openId=0844bd4f-2a0c-4d68-960f-f80382457f8a` 或是 `http://localhost:5230/api/memo?openId=33c3700d-831e-4bc7-baba-0a656ee32b2b` 这样的吗？
> 
> 如果方便的话你可以单独发我你的链接，我帮你测试一下

对的 就是类似这样的链接 是在memos后台复制的

**Comment by tsaoshuang** [comment]
> 我这里是可以的，你填入的链接是类似 `http://localhost:5230/api/v1/memo?openId=0844bd4f-2a0c-4d68-960f-f80382457f8a` 或是 `http://localhost:5230/api/memo?openId=33c3700d-831e-4bc7-baba-0a656ee32b2b` 这样的吗？
> 
> 如果方便的话你可以单独发我你的链接，我帮你测试一下

如何私发你

**Comment by hyoban** [comment]
我的邮箱 hi@hyoban.cc 或者 tg 联系我 t.me/hyoban

**Comment by tsaoshuang** [comment]
> 我的邮箱 [hi@hyoban.cc](mailto:hi@hyoban.cc) 或者 tg 联系我 t.me/hyoban

tg发过去了

**Comment by hyoban** [comment]
![ScreenShot 2023-08-12 14 13 42](https://github.com/hyoban/obsidian-memos-plugin/assets/38493346/1ddd5e9c-df9a-4ed9-b94d-521d1f3cb411)

如果打开控制台看到类似这样的报错的话，或许是服务器证书配置的原因？
不太确定我是否应该按照如下提到方式来禁用 TLS 检查，https://stackoverflow.com/q/31673587

**Comment by tsaoshuang** [comment]
> ![ScreenShot 2023-08-12 14 13 42](https://user-images.githubusercontent.com/38493346/260205989-1ddd5e9c-df9a-4ed9-b94d-521d1f3cb411.png)
> 
> 如果打开控制台看到类似这样的报错的话，或许是服务器证书配置的原因？ 不太确定我是否应该按照如下提到方式来禁用 TLS 检查，https://stackoverflow.com/q/31673587

OK 我再查查资料
