### ISSUE TITLE
从Memos导入OB样式问题

### ISSUE THREAD

**Issue by ZhXWei** [hyoban/obsidian-memos-plugin#8]
您好，感谢您的插座，让输入直接从Memos进OB。
目前文件的格式按照单条创建文件。
能否参照Obsidian Memos插件的方式，直接结合核心插件日志按照日期【YYYYMMDD_ddd-日志】（调用），根据同步API每条的创建日期创建文件或追加。
文件内容格式可定义。
如Obsidian Memos插件可读的格式，【- 22:59 内容】的方式。
资源文件直接放到附件文件夹。
![image](https://github.com/hyoban/obsidian-memos-plugin/assets/29368489/99e878af-127f-4b45-98e8-1953e106f983)

**Comment by hyoban** [comment]
发布了 1.1.0 版本，支持定义文件创建格式，id，创建时间，更新时间，首行文本标题
