### ISSUE TITLE
图片无法同步吗

### ISSUE THREAD

**Issue by somnifex** [hyoban/obsidian-memos-plugin#9]
资源库无法同步

**Comment by hyoban** [comment]
之前试过，应该不管是链接还是文件，都是可以的。你的图片如何存储？

**Comment by somnifex** [comment]
> 之前试过，应该不管是链接还是文件，都是可以的。你的图片如何存储？

七牛云和本地都尝试了，拉不下来

**Comment by hyoban** [comment]
OK，容我测试一下再反馈给你

**Comment by somnifex** [comment]
> 

okk感谢

**Comment by somnifex** [comment]
> OK，容我测试一下再反馈给你

测试结果咋样，需要我提供一下我的用例啥的吗

**Comment by hpsls** [comment]
我这边从一开始就有这个问题，资源文件只能拉取到最新的一个image。看了下源码，问题出在kiraka过滤资源文件的这段
<img width="549" alt="image" src="https://github.com/hyoban/obsidian-memos-plugin/assets/12387736/75068836-52ae-4778-aede-147c14d0c5e9">
对于同名的文件，我改了下把资源id加上就可以了，不过我的变更主要是自己用就没提上来了

**Comment by hyoban** [comment]
@how1ewu 不好意思，最近在准备面试，没看这边。

试了下，应该是正常的。如果你那边还有问题的话，可以再具体描述一下。或者直接联系 https://t.me/hyoban ，提供一些你的相关信息，我给你排查一下。

![ScreenShot 2023-08-27 18 59 27](https://github.com/hyoban/obsidian-memos-plugin/assets/38493346/c4256c71-a65e-456b-a96c-e5f3585da459)

**Comment by hyoban** [comment]
@hpsls 非常感谢，这里用来去重的 id 选错了

**Comment by hyoban** [comment]
1.1.2 版本中应该已经修复
